#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
    set -- apache2-foreground "$@"
fi

if [ -z "$(ls -A /mnt/apps/symfony/www)" ]; then
    cd /mnt/apps/symfony/
    composer create-project symfony/skeleton www
fi

cd /mnt/apps/symfony

# composer install
# npm install

exec "$@"